language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

jobs:
  include:
    - stage: Production
      name: npm_release
      node_js: '12'
      before_script:
        - npm run build
      if: (branch = master OR branch = next) AND env(TRAVIS_PULL_REQUEST) IS false
      script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
